<?php include "../auth.php"; 
		include('../db_conn.php');
		include "../classes/functions.php";
	$kalData_tmp = mysql_query("SELECT * FROM lernstand.kalender");
	echo "<table border =\"1\">";
	while($row = mysql_fetch_assoc($kalData_tmp))
			{
				echo "<tr>";
				
				echo "<td colspan=\"3\">".$row['datum_von']."</td>";
				echo "<td>".$row['zeit_von']."</td>";
				echo "<td rowspan=\"2\">".$row['titel_kurz']."</td>";
				echo "<td rowspan=\"2\">".$row['titel_lang']."</td>";
				echo "<td rowspan=\"2\">".$row['ort']."</td>";
				echo "<td rowspan=\"2\">".$row['web']."</td>";
				echo "<td rowspan=\"2\">".$row['kal_56']."</td>";
				echo "<td rowspan=\"2\">".$row['kal_712']."</td>";
				echo "<td rowspan=\"2\">".$row['kal_lehrer']."</td>";
				echo "<td rowspan=\"2\">".$row['alle']."</td>";
				echo "<td rowspan=\"2\">";
					echo "<a href=\"edit.php\"><img src=\"edit.png\" name=\"edit\" width=\"25px\" height=\"25px\" title=\"Termin bearbeiten\"></a>";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<a href=\"delete\"><img src=\"delete.jpeg\" name=\"delete\" width=\"25px\" height=\"25px\" title=\"Termin L&ouml;schen\"></a>";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td colspan=\"3\">".$row['datum_bis']."</td>";
				echo "<td>".$row['zeit_bis']."</td>";
				
				echo "</tr>";
			}
		echo "<form action=\"cal_data_into_db.php\" method=\"POST\">";
			echo "<tr>";
				echo "<td>";
					echo tag('datum_von_tag');
				echo "</td>";
				echo "<td>";
					echo monat('datum_von_monat');
				echo "</td>";
				echo "<td>";
					echo jahr('datum_von_jahr');
				echo "</td>";
				echo "<td>";
					echo "<input type=\"text\" name=\"zeit_von\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"text\" name=\"titel_kurz\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"text\" name=\"titel_lang\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"text\" name=\"ort\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"checkbox\" name=\"web\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"checkbox\" name=\"kal_56\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"checkbox\" name=\"kal_712\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"checkbox\" name=\"kal_lehrer\">";
				echo "</td>";
				echo "<td rowspan=\"2\">";
					echo "<input type=\"checkbox\" name=\"alle\">";
				echo "</td>";
				echo "<td rowspan=\"2\" colspan=\"3\" align=\"center\">";
					echo "<input type=\"image\" src=\"new.png\" name=\"new\" title=\"Neuen Termin speichern\"></a>";
				echo "</td>";
			echo "</tr>";
			echo "<tr>";
				echo "<td>";
					echo tag('datum_bis_tag');
				echo "</td>";
				echo "<td>";
					echo monat('datum_bis_monat');
				echo "</td>";
				echo "<td>";
					echo jahr('datum_bis_jahr');
				echo "</td>";
				echo "<td>";
					echo "<input type=\"text\" name=\"zeit_bis\">";
				echo "</td>";
			echo "</tr>";
			echo "<input type=\"hidden\" name=\"eingetragen_von\" value=".$_SESSION['uid'].">";	
		echo "</form>";
	echo "</table>";
	
	mysql_close($verbindung);