<html>
<head>
<link type="text/css" rel="stylesheet" href="auswertung.css" />
</head>
<body>


<?php
if($_POST['pw'] == "gemuesesuppe") {} 
else {
  die("So nicht!");
}
$verbindung = mysql_connect ("localhost",
"root", "Kallimann")
or die ("keine Verbindung möglich.
 Benutzername oder Passwort sind falsch");

mysql_select_db("lernstand")
or die ("Die Datenbank existiert nicht.");

$_5_1_soll = mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '5/1'  "));
$_5_1_Ma_haben = mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '5/1' "));
$_5_1_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '5/1' "));;
$_5_1_MNT_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'MNT') and schuelerdaten.klasse = '5/1' "));;
$_5_1_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '5/1' "));;
$_5_1_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '5/1' "));;
$_5_1_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '5/1' "));;
$_5_2_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '5/2'  "));
$_5_2_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '5/2' "));;
$_5_2_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '5/2' "));;
$_5_2_MNT_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'MNT') and schuelerdaten.klasse = '5/2' "));;
$_5_2_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '5/2' "));;
$_5_2_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '5/2' "));;
$_5_2_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '5/2' "));;
$_5_3_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '5/3'  "));
$_5_3_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '5/3' "));;
$_5_3_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '5/3' "));;
$_5_3_MNT_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'MNT') and schuelerdaten.klasse = '5/3' "));;
$_5_3_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '5/3' "));;
$_5_3_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '5/3' "));;
$_5_3_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '5/3' "));;
$_6a_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '6a'  "));
$_6a_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '6a' "));;
$_6a_MNT_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'MNT') and schuelerdaten.klasse = '6a' "));;
$_6a_2FS_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = '2.FS') and schuelerdaten.klasse = '6a' "));;
$_6a_Mu_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Mu') and schuelerdaten.klasse = '6a' "));;
$_6a_Ku_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ku') and schuelerdaten.klasse = '6a' "));;
$_6a_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '6a' "));;
$_6b_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '6b'  "));
$_6b_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '6b' "));;
$_6b_MNT_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'MNT') and schuelerdaten.klasse = '6b' "));;
$_6b_2FS_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = '2.FS') and schuelerdaten.klasse = '6b' "));;
$_6b_Mu_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Mu') and schuelerdaten.klasse = '6b' "));;
$_6b_Ku_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ku') and schuelerdaten.klasse = '6b' "));;
$_6b_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '6b' "));;
$_7a_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '7a'  "));
$_7a_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '7a' "));;
$_7a_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '7a' "));;
$_7a_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '7a' "));;
$_7a_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '7a' "));;
$_7a_Ku_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ku') and schuelerdaten.klasse = '7a' "));;
$_7a_Bio_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Bio') and schuelerdaten.klasse = '7a' "));;
$_7a_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '7a' "));;
$_7b_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '7b'  "));
$_7b_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '7b' "));;
$_7b_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '7b' "));;
$_7b_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '7b' "));;
$_7b_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '7b' "));;
$_7b_Ku_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ku') and schuelerdaten.klasse = '7b' "));;
$_7b_Bio_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Bio') and schuelerdaten.klasse = '7b' "));;
$_7b_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '7b' "));;
$_7c_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '7c'  "));
$_7c_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '7c' "));;
$_7c_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '7c' "));;
$_7c_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '7c' "));;
$_7c_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '7c' "));;
$_7c_Ku_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ku') and schuelerdaten.klasse = '7c' "));;
$_7c_Bio_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Bio') and schuelerdaten.klasse = '7c' "));;
$_7c_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '7c' "));;
$_8a_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '8a'  "));
$_8a_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '8a' "));;
$_8a_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '8a' "));;
$_8a_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '8a' "));;
$_8a_2FS_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = '2.FS') and schuelerdaten.klasse = '8a' "));;
$_8a_Mu_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Mu') and schuelerdaten.klasse = '8a' "));;
$_8a_Ph_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ph') and schuelerdaten.klasse = '8a' "));;
$_8a_Ch_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ch') and schuelerdaten.klasse = '8a' "));;
$_8b_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '8b'  "));
$_8b_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '8b' "));;
$_8b_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '8b' "));;
$_8b_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '8b' "));;
$_8b_2FS_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = '2.FS') and schuelerdaten.klasse = '8b' "));;
$_8b_Mu_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Mu') and schuelerdaten.klasse = '8b' "));;
$_8b_Ph_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ph') and schuelerdaten.klasse = '8b' "));;
$_8b_Ch_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ch') and schuelerdaten.klasse = '8b' "));;
$_8c_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '8c'  "));
$_8c_Sp_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Sp') and schuelerdaten.klasse = '8c' "));;
$_8c_Ge_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ge') and schuelerdaten.klasse = '8c' "));;
$_8c_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '8c' "));;
$_8c_2FS_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = '2.FS') and schuelerdaten.klasse = '8c' "));;
$_8c_Mu_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Mu') and schuelerdaten.klasse = '8c' "));;
$_8c_Ph_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ph') and schuelerdaten.klasse = '8c' "));;
$_8c_Ch_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ch') and schuelerdaten.klasse = '8c' "));;
$_9a_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '9a'  "));
$_9a_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '9a' "));;
$_9a_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '9a' "));;
$_9a_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '9a' "));;
$_9a_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '9a' "));;
$_9a_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '9a' "));;
$_9a_WPF_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'WPF') and schuelerdaten.klasse = '9a' "));;
$_9b_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '9b'  "));
$_9b_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '9b' "));;
$_9b_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '9b' "));;
$_9b_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '9b' "));;
$_9b_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '9b' "));;
$_9b_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '9b' "));;
$_9b_WPF_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'WPF') and schuelerdaten.klasse = '9b' "));;
$_9c_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '9c'  "));
$_9c_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '9c' "));;
$_9c_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '9c' "));;
$_9c_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '9c' "));;
$_9c_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '9c' "));;
$_9c_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '9c' "));;
$_9c_WPF_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'WPF') and schuelerdaten.klasse = '9c' "));;
$_9d_soll= mysql_num_rows(mysql_query("SELECT * FROM schuelerdaten WHERE klasse = '9d'  "));
$_9d_Ma_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Ma') and schuelerdaten.klasse = '9d' "));;
$_9d_De_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'De') and schuelerdaten.klasse = '9d' "));;
$_9d_En_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'En') and schuelerdaten.klasse = '9d' "));;
$_9d_Geo_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Geo') and schuelerdaten.klasse = '9d' "));;
$_9d_Eth_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'Eth/Re') and schuelerdaten.klasse = '9d' "));;
$_9d_WPF_haben= mysql_num_rows(mysql_query("select * from schuelerdaten where not exists (select * from bewertung where schuelerdaten.uid = bewertung.uid and bewertung.fach = 'WPF') and schuelerdaten.klasse = '9d' "));;

mysql_close($verbindung); 


?>

<h2>Stand der Bewertungen<h2>
<table border="1">
<tr>
<th>Klasse</th><th>Fach</th><th>Anzahl Sch&uuml;ler</th><th>bewertet</th><th>noch zu bewerten</th><th>Status</th>
</tr>
<tr><td>5/1</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="5/1"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_Ma_haben ?></td><td><?php echo $_5_1_Ma_haben ?></td><td><?php if($_5_1_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_En_haben ?></td><td><?php echo $_5_1_En_haben ?></td><td><?php if($_5_1_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>MNT</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_MNT_haben ?></td><td><?php echo $_5_1_MNT_haben ?></td><td><?php if($_5_1_MNT_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Sp</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_Sp_haben ?></td><td><?php echo $_5_1_Sp_haben ?></td><td><?php if($_5_1_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_Ge_haben ?></td><td><?php echo $_5_1_Ge_haben ?></td><td><?php if($_5_1_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_5_1_soll ?></td><td><?php echo $_5_1_soll - $_5_1_Geo_haben ?></td><td><?php echo $_5_1_Geo_haben ?></td><td><?php if($_5_1_Geo_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>5/2</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="5/2"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_Ma_haben ?></td><td><?php echo $_5_2_Ma_haben ?></td><td><?php if($_5_2_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_En_haben ?></td><td><?php echo $_5_2_En_haben ?></td><td><?php if($_5_2_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>MNT</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_MNT_haben ?></td><td><?php echo $_5_2_MNT_haben ?></td><td><?php if($_5_2_MNT_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Sp</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_Sp_haben ?></td><td><?php echo $_5_2_Sp_haben ?></td><td><?php if($_5_2_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_Ge_haben ?></td><td><?php echo $_5_2_Ge_haben ?></td><td><?php if($_5_2_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_5_2_soll ?></td><td><?php echo $_5_2_soll - $_5_2_Geo_haben ?></td><td><?php echo $_5_2_Geo_haben ?></td><td><?php if($_5_2_Geo_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>5/3</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="5/3"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_Ma_haben ?></td><td><?php echo $_5_3_Ma_haben ?></td><td><?php if($_5_3_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_En_haben ?></td><td><?php echo $_5_3_En_haben ?></td><td><?php if($_5_3_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>MNT</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_MNT_haben ?></td><td><?php echo $_5_3_MNT_haben ?></td><td><?php if($_5_3_MNT_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Sp</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_Sp_haben ?></td><td><?php echo $_5_3_Sp_haben ?></td><td><?php if($_5_3_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_Ge_haben ?></td><td><?php echo $_5_3_Ge_haben ?></td><td><?php if($_5_3_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_5_3_soll ?></td><td><?php echo $_5_3_soll - $_5_3_Geo_haben ?></td><td><?php echo $_5_3_Geo_haben ?></td><td><?php if($_5_3_Geo_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>6a</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="6a"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>De</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_De_haben ?></td><td><?php echo $_6a_De_haben ?></td><td><?php if($_6a_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>MNT</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_MNT_haben ?></td><td><?php echo $_6a_MNT_haben ?></td><td><?php if($_6a_MNT_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>2.FS</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_2FS_haben ?></td><td><?php echo $_6a_2FS_haben ?></td><td><?php if($_6a_2FS_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Mu</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_Mu_haben ?></td><td><?php echo $_6a_Mu_haben ?></td><td><?php if($_6a_Mu_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ku</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_Ku_haben ?></td><td><?php echo $_6a_Ku_haben ?></td><td><?php if($_6a_Ku_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth</td><td><?php echo $_6a_soll ?></td><td><?php echo $_6a_soll - $_6a_Eth_haben ?></td><td><?php echo $_6a_Eth_haben ?></td><td><?php if($_6a_Eth_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>6b</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="6b"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>De</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_De_haben ?></td><td><?php echo $_6b_De_haben ?></td><td><?php if($_6b_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>MNT</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_MNT_haben ?></td><td><?php echo $_6b_MNT_haben ?></td><td><?php if($_6b_MNT_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>2.FS</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_2FS_haben ?></td><td><?php echo $_6b_2FS_haben ?></td><td><?php if($_6b_2FS_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Mu</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_Mu_haben ?></td><td><?php echo $_6b_Mu_haben ?></td><td><?php if($_6b_Mu_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ku</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_Ku_haben ?></td><td><?php echo $_6b_Ku_haben ?></td><td><?php if($_6b_Ku_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_6b_soll ?></td><td><?php echo $_6b_soll - $_6b_Eth_haben ?></td><td><?php echo $_6b_Eth_haben ?></td><td><?php if($_6b_Eth_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>7a</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="7a"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_Ma_haben ?></td><td><?php echo $_7a_Ma_haben ?></td><td><?php if($_7a_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_De_haben ?></td><td><?php echo $_7a_De_haben ?></td><td><?php if($_7a_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_En_haben ?></td><td><?php echo $_7a_En_haben ?></td><td><?php if($_7a_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<!--<tr><td></td><td>Geo</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_Geo_haben ?></td><td><?php echo $_7a_Geo_haben ?></td><td><?php if($_7a_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>-->
<tr><td></td><td>Ku</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_Ku_haben ?></td><td><?php echo $_7a_Ku_haben ?></td><td><?php if($_7a_Ku_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_Eth_haben ?></td><td><?php echo $_7a_Eth_haben ?></td><td><?php if($_7a_Eth_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Bio</td><td><?php echo $_7a_soll ?></td><td><?php echo $_7a_soll - $_7a_Bio_haben ?></td><td><?php echo $_7a_Bio_haben ?></td><td><?php if($_7a_Bio_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>7b</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="7b"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_Ma_haben ?></td><td><?php echo $_7b_Ma_haben ?></td><td><?php if($_7b_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_De_haben ?></td><td><?php echo $_7b_De_haben ?></td><td><?php if($_7b_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_En_haben ?></td><td><?php echo $_7b_En_haben ?></td><td><?php if($_7b_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<!--<tr><td></td><td>Geo</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_Geo_haben ?></td><td><?php echo $_7b_Geo_haben ?></td><td><?php if($_7b_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>-->
<tr><td></td><td>Ku</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_Ku_haben ?></td><td><?php echo $_7b_Ku_haben ?></td><td><?php if($_7b_Ku_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_Eth_haben ?></td><td><?php echo $_7b_Eth_haben ?></td><td><?php if($_7b_Eth_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Bio</td><td><?php echo $_7b_soll ?></td><td><?php echo $_7b_soll - $_7b_Bio_haben ?></td><td><?php echo $_7b_Bio_haben ?></td><td><?php if($_7b_Bio_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr> 

<tr><td>7c</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="7c"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_Ma_haben ?></td><td><?php echo $_7c_Ma_haben ?></td><td><?php if($_7c_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_De_haben ?></td><td><?php echo $_7c_De_haben ?></td><td><?php if($_7c_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_En_haben ?></td><td><?php echo $_7c_En_haben ?></td><td><?php if($_7c_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<!--<tr><td></td><td>Geo</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_Geo_haben ?></td><td><?php echo $_7c_Geo_haben ?></td><td><?php if($_7c_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>-->
<tr><td></td><td>Ku</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_Ku_haben ?></td><td><?php echo $_7c_Ku_haben ?></td><td><?php if($_7c_Ku_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_Eth_haben ?></td><td><?php echo $_7c_Eth_haben ?></td><td><?php if($_7c_Eth_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Bio</td><td><?php echo $_7c_soll ?></td><td><?php echo $_7c_soll - $_7c_Bio_haben ?></td><td><?php echo $_7c_Bio_haben ?></td><td><?php if($_7c_Bio_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>8a</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="8a"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Sp</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Sp_haben ?></td><td><?php echo $_8a_Sp_haben ?></td><td><?php if($_8a_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Ge_haben ?></td><td><?php echo $_8a_Ge_haben ?></td><td><?php if($_8a_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Geo_haben ?></td><td><?php echo $_8a_Geo_haben ?></td><td><?php if($_8a_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>2.FS</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_2FS_haben ?></td><td><?php echo $_8a_2FS_haben ?></td><td><?php if($_8a_2FS_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Mu</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Mu_haben ?></td><td><?php echo $_8a_Mu_haben ?></td><td><?php if($_8a_Mu_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ph</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Ph_haben ?></td><td><?php echo $_8a_Ph_haben ?></td><td><?php if($_8a_Ph_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ch</td><td><?php echo $_8a_soll ?></td><td><?php echo $_8a_soll - $_8a_Ch_haben ?></td><td><?php echo $_8a_Ch_haben ?></td><td><?php if($_8a_Ch_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>8b</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="8b"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Sp</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Sp_haben ?></td><td><?php echo $_8b_Sp_haben ?></td><td><?php if($_8b_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Ge_haben ?></td><td><?php echo $_8b_Ge_haben ?></td><td><?php if($_8b_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Geo_haben ?></td><td><?php echo $_8b_Geo_haben ?></td><td><?php if($_8b_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>2.FS</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_2FS_haben ?></td><td><?php echo $_8b_2FS_haben ?></td><td><?php if($_8b_2FS_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Mu</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Mu_haben ?></td><td><?php echo $_8b_Mu_haben ?></td><td><?php if($_8b_Mu_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ph</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Ph_haben ?></td><td><?php echo $_8b_Ph_haben ?></td><td><?php if($_8b_Ph_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ch</td><td><?php echo $_8b_soll ?></td><td><?php echo $_8b_soll - $_8b_Ch_haben ?></td><td><?php echo $_8b_Ch_haben ?></td><td><?php if($_8b_Ch_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>8c</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="8c"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Sp</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Sp_haben ?></td><td><?php echo $_8c_Sp_haben ?></td><td><?php if($_8c_Sp_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ge</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Ge_haben ?></td><td><?php echo $_8c_Ge_haben ?></td><td><?php if($_8c_Ge_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Geo_haben ?></td><td><?php echo $_8c_Geo_haben ?></td><td><?php if($_8c_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>2.FS</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_2FS_haben ?></td><td><?php echo $_8c_2FS_haben ?></td><td><?php if($_8c_2FS_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Mu</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Mu_haben ?></td><td><?php echo $_8c_Mu_haben ?></td><td><?php if($_8c_Mu_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ph</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Ph_haben ?></td><td><?php echo $_8c_Ph_haben ?></td><td><?php if($_8c_Ph_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Ch</td><td><?php echo $_8c_soll ?></td><td><?php echo $_8c_soll - $_8c_Ch_haben ?></td><td><?php echo $_8c_Ch_haben ?></td><td><?php if($_8c_Ch_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>9a</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="9a"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_Ma_haben ?></td><td><?php echo $_9a_Ma_haben ?></td><td><?php if($_9a_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_De_haben ?></td><td><?php echo $_9a_De_haben ?></td><td><?php if($_9a_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_En_haben ?></td><td><?php echo $_9a_En_haben ?></td><td><?php if($_9a_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_Geo_haben ?></td><td><?php echo $_9a_Geo_haben ?></td><td><?php if($_9a_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_Eth_haben ?></td><td><?php echo $_9a_Eth_haben ?></td><td><?php if($_9a_Eth_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>WPF</td><td><?php echo $_9a_soll ?></td><td><?php echo $_9a_soll - $_9a_WPF_haben ?></td><td><?php echo $_9a_WPF_haben ?></td><td><?php if($_9a_WPF_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>9b</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="9b"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_Ma_haben ?></td><td><?php echo $_9b_Ma_haben ?></td><td><?php if($_9b_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_De_haben ?></td><td><?php echo $_9b_De_haben ?></td><td><?php if($_9b_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_En_haben ?></td><td><?php echo $_9b_En_haben ?></td><td><?php if($_9b_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_Geo_haben ?></td><td><?php echo $_9b_Geo_haben ?></td><td><?php if($_9b_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_Eth_haben ?></td><td><?php echo $_9b_Eth_haben ?></td><td><?php if($_9b_Eth_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>WPF</td><td><?php echo $_9b_soll ?></td><td><?php echo $_9b_soll - $_9b_WPF_haben ?></td><td><?php echo $_9b_WPF_haben ?></td><td><?php if($_9b_WPF_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>9c</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="9c"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_Ma_haben ?></td><td><?php echo $_9c_Ma_haben ?></td><td><?php if($_9c_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_De_haben ?></td><td><?php echo $_9c_De_haben ?></td><td><?php if($_9c_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_En_haben ?></td><td><?php echo $_9c_En_haben ?></td><td><?php if($_9c_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_Geo_haben ?></td><td><?php echo $_9c_Geo_haben ?></td><td><?php if($_9c_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_Eth_haben ?></td><td><?php echo $_9c_Eth_haben ?></td><td><?php if($_9c_Eth_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>WPF</td><td><?php echo $_9c_soll ?></td><td><?php echo $_9c_soll - $_9c_WPF_haben ?></td><td><?php echo $_9c_WPF_haben ?></td><td><?php if($_9c_WPF_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>

<tr><td>9d</td><td><form action="makePdf.php" method="POST" ><input  type="submit" value="Druckausgabe erzeugen"><input type="hidden" name="klasse" value="9d"></form></td><td><--work in progress</td></tr>
	<tr><td></td><td>Ma</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_Ma_haben ?></td><td><?php echo $_9d_Ma_haben ?></td><td><?php if($_9d_Ma_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>De</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_De_haben ?></td><td><?php echo $_9d_De_haben ?></td><td><?php if($_9d_De_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>En</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_En_haben ?></td><td><?php echo $_9d_En_haben ?></td><td><?php if($_9d_En_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Geo</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_Geo_haben ?></td><td><?php echo $_9d_Geo_haben ?></td><td><?php if($_9d_Geo_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>Eth/Re</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_Eth_haben ?></td><td><?php echo $_9d_Eth_haben ?></td><td><?php if($_9d_Eth_haben > 0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
<tr><td></td><td>WPF</td><td><?php echo $_9d_soll ?></td><td><?php echo $_9d_soll - $_9d_WPF_haben ?></td><td><?php echo $_9d_WPF_haben ?></td><td><?php if($_9d_WPF_haben >  0){echo "<img src=\"notchecked.jpeg\" width=\"18px\" heigth=\"18px\">";}else{echo "<img src=\"checked.jpeg\" width=\"18px\" heigth=\"18px\">";} ?></td> </tr>
</table>
</body>

</html>





